name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  find-latest-release:
    uses: lf-lang/lingua-franca/.github/workflows/latest-release.yml@master
    
  check-compile:
    runs-on: ubuntu-24.04
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - name: Setup environment
        run: bash ./utils/scripts/setup-env.bash
      - name: Make environment variables persistent
        run: |
          source /opt/ros/*/setup.bash
          printenv >> "$GITHUB_ENV"
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "compile"
          no_compile_flag: false
          exclude_dirs: '["failing", "experiments"]'
          compiler_ref: ${{ needs.find-latest-release.outputs.ref }} # for testing, consider replacing with "master"

  check-format:
    runs-on: ubuntu-24.04
    needs: find-latest-release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        run: |
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        shell: bash
      - uses: lf-lang/action-check-lf-files@main
        with:
          check_mode: "format"
          exclude_dirs: '["failing", "experiments"]'
          compiler_ref: ${{ needs.find-latest-release.outputs.ref }}
